# -*- coding: utf-8 -*-
"""personalize_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQoEL9SHRkhZwF2b6YjkDsbEaFjsghMp
"""

#pip install boto3
import boto3
import botocore
from botocore.exceptions import NoCredentialsError
import uuid
import sys
import argparse
import os
import numpy as np
import time
from scipy.io import wavfile
import personalize_function as pf

# from google.colab import drive

def generate_unique_filename(extension='dat'):
# default extension is 'dat'
  unique_filename = f"{uuid.uuid4()}.{extension}"
  return unique_filename

def download_from_aws(bucket, s3_file, local_file):
    s3 = boto3.client('s3')

    try:
        s3.Bucket(bucket).download_file(s3_file, local_file)
        # print(f"Download Successful: {local_file}")
        return True
    except botocore.exceptions.ClientError as e:
        if e.response['Error']['Code'] == "404":
            print("The object does not exist.")
        else:
            raise
        return False

def upload_to_aws(local_file, bucket, s3_file):
    s3 = boto3.client('s3')

    try:
        s3.upload_file(local_file, bucket, s3_file)
        # print(f"Upload Successful: {s3_file}")
        return True
    except FileNotFoundError:
        # print("The file was not found")
        return False
    except NoCredentialsError:
        # print("Credentials not available")
        return False


def delete_all_local_files(files):
  for file in files:
    if file:
      if os.path.exists(file):
        os.remove(file)

  return True

def get_wav_info(file_path):
    # Get file size
    file_size = os.path.getsize(file_path)

    # Get sample rate and data from the WAV file
    sample_rate, data = wavfile.read(file_path)

    # Calculate the duration in seconds
    duration = int(data.shape[0] / sample_rate)

    return file_size, duration
  
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Personalize Process Example script.')
    # parser.add_argument('--bucket',  required=True, help='[require] The S3 bucket name')
    # parser.add_argument('--raw', required=True, help='[require] The S3 file name of raw data. [wav]')
    # parser.add_argument('--ear', required=True, help='[require] The S3 file name of ear data. [wav]')
    # parser.add_argument('--device', required=True, help='[require] The S3 file name of device data. [wav]')
    # parser.add_argument('--meta', required=False, help='[option ] The S3 file name of meta data. [zip]')
    # parser.add_argument('--output', required=True, help='[require] Output file name for the S3. [wav]')
    parser.add_argument('bucket')
    parser.add_argument('raw')
    parser.add_argument('ear')
    parser.add_argument('device')
    parser.add_argument('meta')
    parser.add_argument('output')

    args = parser.parse_args()

    # Make local file name (avoid conflict file name)
    raw_name = generate_unique_filename('wav')
    ear_name = generate_unique_filename('wav')
    device_name = generate_unique_filename('wav')
    output_name = generate_unique_filename('wav')
    # print("raw   :" +raw_name)
    # print("ear   :"+ear_name)
    # print("device:"+device_name)
    # print("output:"+output_name)
    if args.meta != '':
      meta_name = generate_unique_filename('zip')
      # print("meta  :"+meta_name)
    else :
      meta_name = None
      # print("meta  :")

    local_files = [raw_name, ear_name, device_name, meta_name, output_name]


    # Download & Prepare Files
    try: 
      downloaded = download_from_aws(args.bucket, args.raw, raw_name)
      if not downloaded:
        raise Exception("Failed to download raw data.")
      downloaded = download_from_aws(args.bucket, args.ear, ear_name)
      if not downloaded:
        raise Exception("Failed to download ear data.")

      downloaded = download_from_aws(args.bucket, args.device, device_name)
      if not downloaded:
        raise Exception("Failed to download device data.")

      if meta_name:
        downloaded = download_from_aws(args.bucket, args.meta, meta_name)
        if not downloaded:
          raise Exception("Failed to download meta data.")

      # Convert Data
      convert_result = pf.convert_personalize(raw_name, ear_name, device_name, meta_name, output_name)
      if not convert_result:
        raise Exception("Failed to convert data.")

      url = str("personalize/" + str(int(time.time())) + "_" + args.output)
      uploaded = upload_to_aws(output_name, args.bucket, url)
      if not uploaded:
        raise Exception("Failed to upload data.")

      file_size, duration = get_wav_info(output_name)
      result = { 
                "status": 'succeed',
                "step": 'response',
                "size": file_size,
                "timeRunning" : duration,
                "type": "audio/wav",
                "url": url,
                "name": args.output
                }
      
    except Exception as e:
      result = { 
                "status": 'failed',
                "step": 'response',
                "error": str(e)
                }
      
    finally:
    # Delete Local Files
      delete_all_local_files(local_files)
      print([result])

    # Exit
    sys.exit(0)